services:

  backend:
    build: ./backend
    ports:
      - "9000:9000"
    networks:
      - my_network

  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
