{
 "title": "Flask Web App",
 "description": "Dashboard for official Prometheus Python Client's metrics",
 "tags": [
  "flask",
  "app",
  "web",
  "python"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "app_name",
    "label": "app_name",
    "query": {
     "query": "label_values(request_count_total,app_name)"
    }
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(request_count_created,endpoint)"
    }
   },
   {
    "name": "method",
    "label": "HTTP Method",
    "query": {
     "query": "label_values(request_count_total,method)"
    }
   },
   { "name": "percentile", "label": "Percentile", "query": "100,99,95,90,75,50,25" },
   {
    "name": "error_code",
    "label": "Status code 4xx or 5xx",
    "query": {
     "query": "label_values(request_count_total,http_status)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "Requests per second ",
   "gridPos": { "h": 16, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(request_count_total{app_name=~\"$app_name\",endpoint=~\"$endpoint\", method=~\"$method\"}[$interval])",
     "legendFormat": "{{ app_name }} - {{ endpoint }}"
    }
   ]
  },
  {
   "title": "Request Latency, s",
   "type": "timeseries",
   "description": "Latency per pod, endpoint and method",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_latency_seconds_sum{app_name=~\"$app_name\", endpoint=~\"$endpoint\"}[$interval]) \n/ \nrate(request_latency_seconds_count{app_name=~\"$app_name\", endpoint=~\"$endpoint\"}[$interval])",
     "legendFormat": " {{ app_name}}{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Latency within which $percentile% of requests served",
   "type": "timeseries",
   "description": "See more:\nhttps://prometheus.io/docs/practices/histograms/",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile / 100, sum(rate(request_latency_seconds_bucket[$interval])) by (le))",
     "legendFormat": "latency"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors per second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(request_count_total{http_status=~\"4..|5..\", app_name=~\"$app_name\"}[$interval]))",
     "legendFormat": " Errors per second $app_name"
    }
   ]
  },
  {
   "title": "4xx, 5xx errors count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "request_count_total{http_status=~\"$error_code\", app_name=~\"$app_name\", method=~\"$method\", endpoint=~\"$endpoint\"}",
     "legendFormat": "{{ http_status }} {{ app_name }} {{ endpoint }}"
    },
    {}
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{}[$interval])",
     "legendFormat": "cpu"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "description": "Number of open file descriptors",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "(process_open_fds{})", "legendFormat": "{{ pod }}" }
   ]
  }
 ]
}