global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v2
scrape_configs:
- job_name: prometheus
  honor_timestamps: true
  scrape_interval: 15s
  scrape_timeout: 10s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - localhost:9090

- job_name: 'webapp'
  scrape_interval: 15s
  static_configs:
  - targets: ['host.docker.internal:5000']

- job_name: 'backend'
  scrape_interval: 15s
  static_configs:
  - targets: ['host.docker.internal:9000']
  relabel_configs:
    - source_labels: [__param_target]
      target_label: 'app_name'
      replacement: 'backend'

